In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import skew,kurtosis
import sympy as sp
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RepeatedStratifiedKFold

In [36]:
from imblearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [37]:
df=pd.read_csv('diet_recommendation_dataset_1000.csv')

In [38]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic


In [39]:
x=df.drop(columns=['Diet'])
y=df['Diet']

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,stratify=y,random_state=42)

In [41]:
knn = KNeighborsClassifier()
rf = RandomForestClassifier(random_state=42)

rfecv = RFECV(
    estimator=rf,
    step=1,
    cv=StratifiedKFold(5),
    scoring='accuracy'
)

In [42]:
pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('smote',SMOTE(random_state=42)),
    ('feature_selection',rfecv),
    ('knn',KNeighborsClassifier(n_neighbors=5))
])

In [43]:
model1=pipeline.fit(x_train,y_train)

In [44]:
y_pred = model1.predict(x_test)

In [45]:
y_pred

array(['Heart Healthy', 'Low Carb', 'Low Carb', 'Diabetic', 'Diabetic',
       'Low Carb', 'Heart Healthy', 'Diabetic', 'Low Carb',
       'Heart Healthy', 'Heart Healthy', 'Diabetic', 'Low Carb',
       'Diabetic', 'Heart Healthy', 'Diabetic', 'Diabetic',
       'High Protein', 'Diabetic', 'Heart Healthy', 'High Protein',
       'Heart Healthy', 'Diabetic', 'Low Carb', 'Heart Healthy',
       'Diabetic', 'Diabetic', 'Low Carb', 'Diabetic', 'Heart Healthy',
       'Low Carb', 'Diabetic', 'Diabetic', 'Diabetic', 'Heart Healthy',
       'Diabetic', 'Balanced', 'Low Carb', 'Low Carb', 'Heart Healthy',
       'Heart Healthy', 'Diabetic', 'High Protein', 'Balanced',
       'Balanced', 'Low Carb', 'Heart Healthy', 'Balanced', 'Low Carb',
       'Low Carb', 'Low Carb', 'Low Carb', 'Diabetic', 'Diabetic',
       'Low Carb', 'Diabetic', 'Diabetic', 'Low Carb', 'Low Carb',
       'High Protein', 'High Protein', 'Diabetic', 'Heart Healthy',
       'High Protein', 'High Protein', 'Diabetic', 'Diab

In [46]:
accuracy_score(y_test,y_pred)

0.732

In [47]:
confusion_matrix(y_test,y_pred)

array([[ 9,  0,  0,  1,  1],
       [ 3, 93, 12,  7, 20],
       [ 0,  0, 18,  3,  2],
       [ 0,  0,  2, 15,  0],
       [ 4,  6,  6,  0, 48]], dtype=int64)

In [48]:
print(classification_report(y_test,y_pred))

               precision    recall  f1-score   support

     Balanced       0.56      0.82      0.67        11
     Diabetic       0.94      0.69      0.79       135
Heart Healthy       0.47      0.78      0.59        23
 High Protein       0.58      0.88      0.70        17
     Low Carb       0.68      0.75      0.71        64

     accuracy                           0.73       250
    macro avg       0.65      0.78      0.69       250
 weighted avg       0.79      0.73      0.74       250



## KNN Model With forkward Features selected

In [49]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic


In [197]:
x=df.drop(columns=['Diet'])

y=df['Diet']
le=LabelEncoder()
y=le.fit_transform(y)
y

xtrain1,xtest1,ytrain1,ytest1=train_test_split(x,y)

In [198]:
knn = KNeighborsClassifier(n_neighbors=5)

sfs = SequentialFeatureSelector(
        knn,
        n_features_to_select=5,
        direction='forward',
        cv=5,
        scoring='accuracy'
)

In [199]:
pipeline1 = Pipeline([
    ('scaler', StandardScaler()),
    ('feature_selection', sfs),  
    ('smote', SMOTE(random_state=42)),
    ('knn', knn)
])

model2=pipeline1.fit(xtrain1,ytrain1)

y_pred1= model2.predict(xtest1)

In [200]:
accuracy_score(ytest1,y_pred1)

0.88

In [202]:
confusion_matrix(ytest1,y_pred1)

array([[ 12,   1,   0,   0,   0],
       [  1, 118,   2,   6,   7],
       [  0,   0,  26,   1,   1],
       [  0,   0,   1,  15,   0],
       [  1,   5,   4,   0,  49]], dtype=int64)

In [203]:
print(classification_report(ytest1,y_pred1))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89        13
           1       0.95      0.88      0.91       134
           2       0.79      0.93      0.85        28
           3       0.68      0.94      0.79        16
           4       0.86      0.83      0.84        59

    accuracy                           0.88       250
   macro avg       0.83      0.90      0.86       250
weighted avg       0.89      0.88      0.88       250



## KNN Model With Forward Features selected Using Hyperparameter Tuning

In [204]:
param_grid = {
    'knn__n_neighbors':[3,5,7,9,11],
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

In [205]:
import time

In [206]:
grid = GridSearchCV(
        pipeline1,
        param_grid,
        cv=5,
        scoring='f1_macro',
        n_jobs=-1
)
start = time.time()

grid.fit(xtrain1,ytrain1)
end = time.time()

print("Time taken:", (end - start)/60, "minutes")

Time taken: 2.765944806734721 minutes


In [207]:
model3=grid.best_estimator_

In [208]:
ypred3=model3.predict(xtest1)

In [209]:
accuracy_score(ytest1,ypred3)

0.864

In [214]:
confusion_matrix(ytest1,ypred3)

array([[ 12,   1,   0,   0,   0],
       [  2, 114,   4,   6,   8],
       [  0,   0,  23,   3,   2],
       [  0,   0,   1,  15,   0],
       [  1,   3,   3,   0,  52]], dtype=int64)

In [215]:
print(classification_report(ytest1,ypred3))

              precision    recall  f1-score   support

           0       0.80      0.92      0.86        13
           1       0.97      0.85      0.90       134
           2       0.74      0.82      0.78        28
           3       0.62      0.94      0.75        16
           4       0.84      0.88      0.86        59

    accuracy                           0.86       250
   macro avg       0.79      0.88      0.83       250
weighted avg       0.88      0.86      0.87       250



## KNN Model With Backward Features selected

In [216]:
x1=df.drop(columns=['Diet'])

y1=df['Diet']
le=LabelEncoder()
y1=le.fit_transform(y)
y1

xtrain2,xtest2,ytrain2,ytest2=train_test_split(x1,y1)

In [217]:
sbs = SequentialFeatureSelector(
        knn,
        n_features_to_select=5,
        direction='backward',
        cv=5,
        scoring='accuracy'
)

In [218]:
pipeline2= Pipeline([
    ('scaler',StandardScaler()),
    ('smote',SMOTE(random_state=42)),
    ('feature_selection',sbs),
    ('knn',KNeighborsClassifier(n_neighbors=5))
])

In [219]:
model4=pipeline2.fit(xtrain2,ytrain2)

In [220]:
y_pred2= model4.predict(xtest2)
y_pred2

array([1, 4, 4, 3, 4, 2, 4, 4, 1, 4, 2, 1, 4, 1, 1, 4, 1, 4, 2, 2, 4, 1,
       1, 1, 1, 4, 4, 3, 2, 1, 4, 4, 1, 1, 2, 1, 4, 1, 1, 1, 1, 3, 1, 0,
       1, 4, 1, 3, 2, 1, 1, 2, 4, 4, 1, 2, 4, 4, 1, 0, 1, 2, 4, 2, 1, 4,
       1, 4, 1, 1, 0, 1, 4, 4, 1, 4, 1, 1, 1, 0, 3, 1, 1, 1, 1, 4, 1, 1,
       4, 4, 4, 1, 1, 2, 1, 3, 1, 3, 1, 2, 4, 1, 3, 1, 3, 4, 1, 1, 4, 1,
       1, 4, 1, 4, 1, 1, 1, 4, 1, 4, 1, 1, 4, 1, 1, 3, 0, 1, 1, 3, 4, 1,
       1, 1, 3, 1, 1, 1, 2, 1, 4, 0, 2, 1, 1, 1, 4, 4, 1, 1, 4, 4, 1, 4,
       3, 1, 4, 4, 1, 1, 4, 1, 2, 4, 0, 1, 1, 1, 1, 3, 4, 2, 3, 1, 4, 1,
       0, 3, 0, 2, 1, 1, 1, 4, 1, 1, 4, 1, 1, 1, 1, 1, 4, 1, 1, 2, 4, 4,
       1, 1, 1, 2, 2, 0, 2, 1, 0, 1, 3, 1, 2, 1, 1, 1, 1, 3, 2, 4, 1, 1,
       1, 1, 4, 4, 1, 1, 1, 1, 4, 2, 1, 3, 2, 1, 4, 4, 4, 3, 2, 2, 4, 2,
       1, 4, 1, 1, 1, 4, 1, 1], dtype=int64)

In [221]:
accuracy_score(ytest2,y_pred2)

0.868

In [222]:
confusion_matrix(ytest2,y_pred2)

array([[  7,   0,   0,   0,   0],
       [  1, 120,   3,   5,   8],
       [  0,   1,  18,   0,   1],
       [  1,   0,   1,  15,   0],
       [  2,   3,   7,   0,  57]], dtype=int64)

In [223]:
print(classification_report(ytest2,y_pred2))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78         7
           1       0.97      0.88      0.92       137
           2       0.62      0.90      0.73        20
           3       0.75      0.88      0.81        17
           4       0.86      0.83      0.84        69

    accuracy                           0.87       250
   macro avg       0.77      0.90      0.82       250
weighted avg       0.89      0.87      0.87       250



## KNN Model With Backward Features selected Using Hyperparameter Tuning

In [150]:
param_grid = {
    'knn__n_neighbors':[3,5,7,9,11],
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}
from sklearn.model_selection import GridSearchCV


In [159]:
grid = GridSearchCV(
        pipeline2,
        param_grid,
        cv=5,
        scoring='accuracy',
        n_jobs=-1
)
start = time.time()

model5=grid.fit(xtrain2,ytrain2)

end = time.time()

print("Time taken:", end - start, "seconds")

Time taken: 337.2065460681915 seconds


In [198]:
model5.best_params_

{'knn__metric': 'manhattan',
 'knn__n_neighbors': 3,
 'knn__weights': 'distance',
 'smote__k_neighbors': 5}

In [199]:
y_pred3=model5.predict(xtest2)

In [200]:
accuracy_score(ytest2,y_pred3)

0.908

In [165]:
from sklearn.metrics import f1_score,recall_score

In [169]:
f1_score(ytest2, y_pred3, average='macro')

0.8941140547635434

In [168]:
recall_score(ytest2, y_pred3, average='macro')

0.9276058201058202

In [163]:
confusion_matrix(ytest2,y_pred3)

array([[ 15,   0,   0,   0,   0],
       [  0, 119,   1,   5,  10],
       [  0,   0,  20,   0,   1],
       [  1,   1,   0,  13,   0],
       [  1,   2,   1,   0,  60]], dtype=int64)

In [164]:
print(classification_report(ytest2,y_pred3))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94        15
           1       0.98      0.88      0.93       135
           2       0.91      0.95      0.93        21
           3       0.72      0.87      0.79        15
           4       0.85      0.94      0.89        64

    accuracy                           0.91       250
   macro avg       0.87      0.93      0.89       250
weighted avg       0.92      0.91      0.91       250



## hyperparameter Tuning on backward Features Model where scoring f1_marco

In [170]:
param_grid = {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

In [171]:
grid1= GridSearchCV(
        pipeline2,
        param_grid,
        cv=5,
        scoring='f1_macro',
        n_jobs=-1
)


start = time.time()

model6=grid1.fit(xtrain2,ytrain2)
end = time.time()

print("Time taken:", (end - start)/2, "minutes")

Time taken: 933.4955768585205 seconds


In [172]:
grid1.best_params_

{'knn__metric': 'manhattan',
 'knn__n_neighbors': 3,
 'knn__weights': 'distance',
 'smote__k_neighbors': 5}

In [173]:
grid1.best_score_

0.8075059229726562

In [174]:
ypred4=model6.predict(xtest2)

In [178]:
accuracy_score(ytest2,ypred4)

0.908

In [179]:
confusion_matrix(ytest2,ypred4)

array([[ 15,   0,   0,   0,   0],
       [  0, 119,   1,   5,  10],
       [  0,   0,  20,   0,   1],
       [  1,   1,   0,  13,   0],
       [  1,   2,   1,   0,  60]], dtype=int64)

In [180]:
print(classification_report(ytest2,ypred4))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94        15
           1       0.98      0.88      0.93       135
           2       0.91      0.95      0.93        21
           3       0.72      0.87      0.79        15
           4       0.85      0.94      0.89        64

    accuracy                           0.91       250
   macro avg       0.87      0.93      0.89       250
weighted avg       0.92      0.91      0.91       250



## hyperparameter Tuning on backward Features Model where cv = StratifiedKFolf

In [ ]:
param_grid= {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid2= GridSearchCV(
        pipeline2,
        param_grid,
        cv=skf,
        scoring='accuracy',
        n_jobs=-1
)


start = time.time()

grid2.fit(xtrain2,ytrain2)
end = time.time()

print("Time taken:", (end - start)/60, "minutes")

In [192]:
grid2.best_params_

{'knn__metric': 'manhattan',
 'knn__n_neighbors': 9,
 'knn__weights': 'distance',
 'smote__k_neighbors': 7}

In [193]:
grid2.best_score_

0.868

In [194]:
ypred5=grid2.best_estimator_.predict(xtest2)

In [195]:
accuracy_score(ytest2,ypred5)

0.872

In [196]:
confusion_matrix(ytest2,ypred5)

array([[ 15,   0,   0,   0,   0],
       [  1, 114,   2,   4,  14],
       [  0,   0,  19,   1,   1],
       [  1,   0,   0,  14,   0],
       [  5,   0,   3,   0,  56]], dtype=int64)

In [197]:
print(classification_report(ytest2,ypred5))

              precision    recall  f1-score   support

           0       0.68      1.00      0.81        15
           1       1.00      0.84      0.92       135
           2       0.79      0.90      0.84        21
           3       0.74      0.93      0.82        15
           4       0.79      0.88      0.83        64

    accuracy                           0.87       250
   macro avg       0.80      0.91      0.84       250
weighted avg       0.89      0.87      0.88       250



## hyperparameter Tuning on backward Features Model where cv = RepeatedStratifiedKFold

In [149]:
param_grid= {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

In [150]:
from sklearn.model_selection import RepeatedStratifiedKFold

In [151]:
cv = RepeatedStratifiedKFold(
        n_splits=5,
        n_repeats=3,
        random_state=42
)

In [152]:
grid3= GridSearchCV(
        pipeline2,
        param_grid,
        cv=cv,
        scoring='f1_macro',
        n_jobs=-1
)


start = time.time()

model8=grid3.fit(xtrain2,ytrain2)
end = time.time()

print("Time taken:", end - start, "seconds")

Time taken: 1716.1279036998749 seconds


In [153]:
grid3.best_params_

{'knn__metric': 'manhattan',
 'knn__n_neighbors': 3,
 'knn__weights': 'distance',
 'smote__k_neighbors': 3}

In [154]:
ypred6=model8.predict(xtest2)

In [155]:
accuracy_score(ytest2,ypred6)

0.856

In [156]:
confusion_matrix(ytest2,ypred6)

array([[  9,   1,   0,   0,   0],
       [  1, 118,   2,   4,   5],
       [  0,   0,  24,   3,   3],
       [  5,   0,   3,  15,   0],
       [  3,   1,   5,   0,  48]], dtype=int64)

In [157]:
print(classification_report(ytest2,ypred6))

              precision    recall  f1-score   support

           0       0.50      0.90      0.64        10
           1       0.98      0.91      0.94       130
           2       0.71      0.80      0.75        30
           3       0.68      0.65      0.67        23
           4       0.86      0.84      0.85        57

    accuracy                           0.86       250
   macro avg       0.75      0.82      0.77       250
weighted avg       0.87      0.86      0.86       250



In [ ]:
y=grid3.best_estimator_.predict(xtest2)

accuracy_score(ytest2,y)

In [ ]:
max_score=0
combo_score=0
best_score=0
best_combinations=[]
x_scaled=ss.fit_transform(x)
model=KNeighborsClassifier(n_neighbors=5)

for i in range(n):
    for j in range(i+1,n):
        for k in range(j+1,n):
            for l in range(k+1,n):
                for m in range(l+1,n):
                    combinations=[i,j,k,l,m]
                    x_values=x_scaled[:,combinations]
                    accuracy_scv=cross_val_score(model,x_values,y,scoring='accuracy',cv=5)
                    max_score=accuracy_scv.mean()
                    if max_score>best_score:
                        best_score=max_score
                        best_combinations=combinations

print(best_score)
print(best_combinations)
best_f=[]
for i in best_combinations:
    print(features[i])
    best_f.append(features[i])
best_f

In [50]:
max_score = 0
best_score = 0
best_combinations = []
features=list(x.columns)

n=len(features)
n
from imblearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.neighbors import KNeighborsClassifier

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for i in range(n):
    for j in range(i+1,n):
        for k in range(j+1,n):
            for l in range(k+1,n):
                for m in range(l+1,n):
                    for o in range(l+1,n):
                    
                        combinations = [i,j,k,l,m,o]
                        x_values = x.iloc[:, combinations]
                        
                        scores = cross_val_score(
                            pipeline,
                            x_values,
                            y,
                            scoring='recall_macro',
                            cv=cv,
                            n_jobs=-1
                        )
                        
                        mean_score = scores.mean()
                        
                        if mean_score > best_score:
                            best_score = mean_score
                            best_combinations = combinations

print(best_score)
print(best_combinations)

best_f = [features[i] for i in best_combinations]
print(best_f)

0.8561398694035193
[0, 1, 2, 3, 4, 4]
['Weight_kg', 'BMI', 'Activity_Level', 'Sugar_Level', 'Cholesterol', 'Cholesterol']


In [51]:
x=x[best_f]

In [42]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic


In [206]:
import pickle

with open('Diet_Recommendation.pkl','wb') as file:
    pickle.dump(model5,file)

print('model saved sucessfully')

model saved sucessfully


In [52]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,stratify=y,random_state=42)

In [53]:
pipeline3= Pipeline([
    ('scaler',StandardScaler()),
    ('smote',SMOTE(random_state=42)),
    ('knn',KNeighborsClassifier(n_neighbors=5))
])

In [54]:
pipeline3.fit(xtrain,ytrain)

Pipeline(steps=[('scaler', StandardScaler()), ('smote', SMOTE(random_state=42)),
                ('knn', KNeighborsClassifier())])

In [55]:
ypred5=pipeline3.predict(xtest)

In [56]:
accuracy_score(ytest,ypred5)

0.88

In [57]:
param_grid= {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid2= GridSearchCV(
        pipeline3,
        param_grid,
        cv=skf,
        scoring='accuracy',
        n_jobs=-1
)


start = time.time()

grid2.fit(xtrain,ytrain)
end = time.time()

print("Time taken:", (end - start)/60, "minutes")

Time taken: 0.08252790371576944 minutes


In [58]:
yy=grid2.best_estimator_.predict(xtest)

In [59]:
accuracy_score(ytest,yy)

0.872

In [78]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic


In [79]:
x=df.drop(columns=['Diet'])

In [81]:
le=LabelEncoder()

In [82]:
y=le.fit_transform(df['Diet'])

In [85]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [86]:
pipeline4=Pipeline(
    [
        ('scler',StandardScaler()),
        ('smote',SMOTE(random_state=42)),
        ('knn',KNeighborsClassifier(n_neighbors=5))
    ]
    
)

In [89]:
pipeline4.fit(xtrain,ytrain)

Pipeline(steps=[('scler', StandardScaler()), ('smote', SMOTE(random_state=42)),
                ('knn', KNeighborsClassifier())])

In [ ]:
yy=pipeline4.predict(xtest)

accuracy_score(ytest,yy)

In [96]:
x.corr()

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal
Age,1.000000,-0.028480,-0.045504,0.031570,0.044260,-0.019433,-0.033849,-0.023504,-0.003518
Gender,-0.028480,1.000000,-0.035237,0.037671,0.048753,-0.047744,-0.000108,0.016309,0.049793
Height_cm,-0.045504,-0.035237,1.000000,-0.020084,-0.487809,0.035577,-0.011179,-0.017428,-0.030967
Weight_kg,0.031570,0.037671,-0.020084,1.000000,0.870239,-0.019191,-0.041038,0.000649,0.015662
BMI,0.044260,0.048753,-0.487809,0.870239,1.000000,-0.034631,-0.026204,0.004125,0.025448
Activity_Level,-0.019433,-0.047744,0.035577,-0.019191,-0.034631,1.000000,0.047111,0.015233,0.000686
Sugar_Level,-0.033849,-0.000108,-0.011179,-0.041038,-0.026204,0.047111,1.000000,0.027882,-0.040996
Cholesterol,-0.023504,0.016309,-0.017428,0.000649,0.004125,0.015233,0.027882,1.000000,0.013310
Goal,-0.003518,0.049793,-0.030967,0.015662,0.025448,0.000686,-0.040996,0.013310,1.000000


In [97]:
x = x[['BMI', 'Activity_Level', 'Sugar_Level', 'Cholesterol', 'Goal']]

In [98]:
x

,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal
0,56.1,0,131,169,2
1,22.5,0,118,253,2
2,28.7,1,78,256,2
3,44.2,2,161,199,0
4,24.4,1,100,237,1
...,...,...,...,...,...
995,17.4,2,172,261,2
996,19.1,2,175,156,2
997,27.7,1,126,177,0
998,14.0,2,149,249,0


In [99]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [101]:
pipeline5=Pipeline(
    [
        ('scler',StandardScaler()),
        ('smote',SMOTE(random_state=42)),
        ('knn',KNeighborsClassifier(n_neighbors=5))
    ]
    
)

In [102]:
pipeline5.fit(xtrain,ytrain)

Pipeline(steps=[('scler', StandardScaler()), ('smote', SMOTE(random_state=42)),
                ('knn', KNeighborsClassifier())])

In [103]:
yy=pipeline5.predict(xtest)

accuracy_score(ytest,yy)

0.856

In [113]:
param_grid= {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid2= GridSearchCV(
        pipeline5,
        param_grid,
        cv=5,
        scoring='accuracy',
        n_jobs=-1
)


start = time.time()

model8=grid2.fit(xtrain,ytrain)
end = time.time()

print("Time taken:", (end - start)/60, "minutes")

Time taken: 0.043415788809458414 minutes


In [114]:
y3=model8.predict(xtest)

accuracy_score(ytest,y3)

0.88

In [115]:
param_grid= {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
    'smote__k_neighbors':[3,5,7]
}

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid2= GridSearchCV(
        pipeline5,
        param_grid,
        cv=skf,
        scoring='accuracy',
        n_jobs=-1
)


start = time.time()

model8=grid2.fit(xtrain,ytrain)
end = time.time()

print("Time taken:", (end - start)/60, "minutes")

Time taken: 0.04388174613316854 minutes


In [116]:
y4=model8.predict(xtest)

accuracy_score(ytest,y4)

0.872

In [117]:
from imblearn.over_sampling import ADASYN

In [132]:
from imblearn.combine import SMOTEENN

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('resample', SMOTEENN(random_state=42)),
    ('knn', KNeighborsClassifier())
])

In [127]:
param_grid= {
    'knn__n_neighbors':range(3,31,2),
    'knn__weights':['uniform','distance'],
    'knn__metric':['euclidean','manhattan'],
}

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid2= GridSearchCV(
        pipeline,
        param_grid,
        cv=skf,
        scoring='accuracy',
        n_jobs=-1
)


start = time.time()

model8=grid2.fit(xtrain,ytrain)
end = time.time()

print("Time taken:", (end - start)/60, "minutes")

Time taken: 0.023927358786265056 minutes


In [128]:
y4=model8.predict(xtest)

accuracy_score(ytest,y4)

0.824